---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: instance
    box: bento/ubuntu-20.04
provisioner:
  name: ansible
verifier:
  name: testinfra
  options: 
    verbose: true
